services:
  anthropic:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./app:/usr/src/app/app
      - ./.env:/usr/src/app/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
